=== dumon/distributed-cache-sample-cluster/dto/src/main/resources/dto-schema/BlogDto.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "BlogDto",
	"type": "object",
	"javaType" : "com.dumon.cache.BlogDto",
	"properties" : {
		"id": { "type": "number" },
		"title": { "type": "string" },
		"post": { "type": "string" },
		"author": { "type": "string" },
		"creationDate": { "type": "string" }
	}
}

=== dumon/distributed-cache-sample-cluster/storage/src/main/resources/blogs.json
[
  {
    "title" : "Blog's title | 1",
    "post" : "blog post content blog post content blog post content blog post content blog post content blog post content",
    "author" : "Bot 1",
    "creationDate" : "2019-03-12 18:10:00"
  },
  {
    "title" : "Blog's title | 2",
    "post" : "blog post content blog post content blog post content blog post content blog post content blog post content",
    "author" : "Bot 2",
    "creationDate" : "2019-03-12 19:10:00"
  },
  {
    "title" : "Blog's title | 3",
    "post" : "blog post content blog post content blog post content blog post content blog post content blog post content",
    "author" : "Bot 3",
    "creationDate" : "2019-03-12 19:10:00"
  },
  {
    "title" : "Blog's title | 4",
    "post" : "blog post content blog post content blog post content blog post content blog post content blog post content",
    "author" : "Bot 4",
    "creationDate" : "2019-03-12 19:10:00"
  },
  {
    "title" : "Blog's title | 5",
    "post" : "blog post content blog post content blog post content blog post content blog post content blog post content",
    "author" : "Bot 5",
    "creationDate" : "2019-03-12 19:10:00"
  }
]
